Revise GitHub actions workflow

diff --git a/.github/workflows/GitHub_Actions_CI.yaml b/.github/workflows/GitHub_Actions_CI.yaml
--- a/.github/workflows/GitHub_Actions_CI.yaml
+++ b/.github/workflows/GitHub_Actions_CI.yaml
@@ -20,12 +20,12 @@ jobs:
       fail-fast: false
       matrix:
         config:
-        - {os: windows-latest, r: 'release', not_cran: 'true', rspm: "https://packagemanager.rstudio.com/all/latest"}
-        - {os: macos-11,   r: 'release', not_cran: 'true', rspm: "https://packagemanager.rstudio.com/all/latest"}
-        - {os: macos-10.15,   r: 'oldrel', not_cran: 'true', rspm:  "https://packagemanager.rstudio.com/all/latest"}
-        - {os: ubuntu-22.04,   r: 'devel', not_cran: 'true', rspm: "https://packagemanager.rstudio.com/all/__linux__/jammy/latest"}
-        - {os: ubuntu-20.04,   r: 'release', not_cran: 'true', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
-        - {os: ubuntu-20.04,   r: 'oldrel', not_cran: 'true', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
+        - {os: windows-latest, r: 'release', not_cran: 'true'}
+        - {os: macOS-latest,   r: 'release', not_cran: 'true'}
+        - {os: macos-10.15,   r: 'oldrel', not_cran: 'true'}
+        - {os: ubuntu-latest,   r: 'devel', not_cran: 'true'}
+        - {os: ubuntu-latest,   r: 'release', not_cran: 'true'}
+        - {os: ubuntu-latest,   r: 'oldrel', not_cran: 'true'}
     env:
       R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
       RSPM: ${{ matrix.config.rspm }}
@@ -35,87 +35,97 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-r@v1
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
         with:
           r-version: ${{ matrix.config.r }}
           http-user-agent: ${{ matrix.config.http-user-agent }}
+          use-public-rspm: true
 
-      - uses: r-lib/actions/setup-pandoc@v1
-
-      - name: Install remotes
-        run: |
-          install.packages('remotes')
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
-        shell: Rscript {0}
-
-      - name: Cache R packages
-        if: runner.os != 'Windows'
-        uses: actions/cache@v1
+      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
-          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-${{ matrix.config.r }}-
+          extra-packages: any::rcmdcheck
+          needs: check
 
-      - name: Install system dependencies
-        if: runner.os == 'Linux'
-        run: |
-          while read -r cmd
-          do
-            eval sudo $cmd
-          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
+      # - name: Install remotes
+      #   run: |
+      #     install.packages('remotes')
+      #     saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
+      #   shell: Rscript {0}
+      #
+      # - name: Cache R packages
+      #   if: runner.os != 'Windows'
+      #   uses: actions/cache@v1
+      #   with:
+      #     path: ${{ env.R_LIBS_USER }}
+      #     key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
+      #     restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-${{ matrix.config.r }}-
+      #
+      # - name: Install system dependencies
+      #   if: runner.os == 'Linux'
+      #   run: |
+      #     while read -r cmd
+      #     do
+      #       eval sudo $cmd
+      #     done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
+      #
+      # - name: Install ghostscript (Linux)
+      #   if: runner.os == 'Linux'
+      #   run: |
+      #     sudo apt-get install -y ghostscript
+      #     sudo apt-get install -y curl
+      #
+      # - name: Install jags (macOS)
+      #   if: runner.os == 'macOS'
+      #   run: brew install jags
+      #
+      # - name: Install jags (Windows)
+      #   if: runner.os == 'windows'
+      #   run: |
+      #      curl --progress-bar -s -o 'C:\JAGS-4.3.1.exe' -L 'https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe'
+      #      C:\JAGS-4.3.1.exe /S
+      #
+      # - name: Install dependencies
+      #   run: |
+      #     remotes::install_deps(dependencies = TRUE)
+      #     remotes::install_cran("rcmdcheck")
+      #     remotes::install_cran("covr")
+      #   shell: Rscript {0}
+      #
+      # - name: Show session info
+      #   run: |
+      #     options(width = 100)
+      #     pkgs <- installed.packages()[, "Package"]
+      #     sessioninfo::session_info(pkgs, include_base = TRUE)
+      #   shell: Rscript {0}
+      #
+      # - name: Remove depends.Rds
+      #   run: |
+      #     unlink("depends.Rds")
+      #   shell: Rscript {0}
 
-      - name: Install ghostscript (Linux)
-        if: runner.os == 'Linux'
-        run: |
-          sudo apt-get install -y ghostscript
-          sudo apt-get install -y curl
+     - uses: r-lib/actions/check-r-package@v2
+       with:
+         upload-snapshots: true
 
-      - name: Install jags (macOS)
-        if: runner.os == 'macOS'
-        run: brew install jags
+      # - name: Check package
+      #   env:
+      #     _R_CHECK_CRAN_INCOMING_: false
+      #   run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+      #   shell: Rscript {0}
 
-      - name: Install jags (Windows)
-        if: runner.os == 'windows'
-        run: |
-           curl --progress-bar -s -o 'C:\JAGS-4.3.1.exe' -L 'https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe'
-           C:\JAGS-4.3.1.exe /S
+      # - name: Show testthat output
+      #   if: always()
+      #   run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #   shell: bash
 
-      - name: Install dependencies
-        run: |
-          remotes::install_deps(dependencies = TRUE)
-          remotes::install_cran("rcmdcheck")
-          remotes::install_cran("covr")
-        shell: Rscript {0}
-
-      - name: Show session info
-        run: |
-          options(width = 100)
-          pkgs <- installed.packages()[, "Package"]
-          sessioninfo::session_info(pkgs, include_base = TRUE)
-        shell: Rscript {0}
-
-      - name: Remove depends.Rds
-        run: |
-          unlink("depends.Rds")
-        shell: Rscript {0}
-
-      - name: Check package
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
-
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
-
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+      # - name: Upload check results
+      #   if: failure()
+      #   uses: actions/upload-artifact@main
+      #   with:
+      #     name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+      #     path: check
 
       - name: Test coverage
         run: |
